/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    kotlin("jvm") version "1.3.61"
}

repositories {
    mavenLocal()
    mavenCentral()
    maven {
        setUrl("http://repo.maven.apache.org/maven2")
    }
}

dependencies {
    implementation(kotlin("stdlib-jdk8"))
    implementation("org.apache.commons:commons-text:1.7")
    testImplementation("junit:junit:4.12")
    testImplementation(kotlin("test"))
    testImplementation(kotlin("test-junit"))
}

group = "com.chausov"
version = "1.0-SNAPSHOT"
description = "Kotlisp"

tasks.jar {
    manifest {
        attributes(
                "Main-Class" to "com.chausov.kotlisp.run.MainKt"
        )
    }
    from(configurations.runtimeClasspath.get().map { if (it.isDirectory) it else zipTree(it) })
}