/*
 * This file was generated by the Gradle 'init' task.
 */

pluginManagement {
    repositories {
        mavenCentral()
        maven { setUrl("https://plugins.gradle.org/m2/") }
    }
}

rootProject.name = "kotlisp"
